[project]
authors = ["Mads B. Kjær <mbk1dk@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "SPAC_week_10"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "*"
